export const CONFIG = {
  yandexMapsApiKey: "8c066d0f-4c17-45c7-88a2-ab37765f4334",
  openWeatherMapApiKey: "c6005872ccdeb15a3c2b2276e57c93a3",
  openWeatherMapTilesApiKey: "c6005872ccdeb15a3c2b2276e57c93a3",
  openWeatherMapWeatherUrl: "https://api.openweathermap.org/data/2.5/weather",
  currencyApiBaseUrl: "https://api.frankfurter.dev/v2",
  countryApiBaseUrl: "https://restcountries.com/v3.1",
  weatherLanguage: "en",
  weatherUnits: "metric",
  requestTimeoutMs: 12000,
  weatherTileOpacity: 0.72,
  defaultView: {
    center: [20, 0],
    zoom: 3,
  },
  worldBounds: [
    [-65, -180],
    [65, 180],
  ],
  baseCurrency: "KZT",
  fallbackLocalCurrency: "USD",
  supportedCurrencies: [
    "USD",
    "EUR",
    "KZT",
    "GBP",
    "JPY",
    "CNY",
    "AUD",
    "CAD",
    "CHF",
    "INR",
    "KRW",
    "TRY",
    "RUB",
    "AED",
    "BRL",
  ],
  weatherTileUrls: {
    temperature:
      "https://tile.openweathermap.org/map/temp_new/%z/%x/%y.png?appid=%apiKey%",
    wind: "https://tile.openweathermap.org/map/wind_new/%z/%x/%y.png?appid=%apiKey%",
  },
};
